apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "project"
    operater: "Equal"
    value: "roboshop"
    effect: "NoSchedule"  