apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-affinity
  labels:
    env: test
spec:
  affinity:
    nodeAffinity:
      # HARD rule - labels must match
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone  # node label key
            operator: In   # must be IN the values list 
            values:  
            - us-east-1d   # only this zone
            - us-east-1c
      preferredDuringSchedulingIgnoredDuringExecution:  
      - weight: 100
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshoppp
      - weight: 10
        preference:
          matchExpressions:
          - key: project
            operator: In
            values: 
            - amazon       
  containers:
  - name: nginx
    image: nginx
